import type { Mission } from './types'

export function testMission(): Mission {
  return {
    id: 'mission-1',
    name: 'Test mission',
    status: 'verified',
    version: 12,
    run_id: 'run-1',
    correlation_id: 'correlation-1',
    execution_mode: 'local_deterministic',
    runtime_telemetry: {
      planning_wall_time_ms: 142,
      verifier_wall_time_ms: 4,
      cover_round_trip_ms: 7,
      qap_round_trip_ms: 2,
      process_peak_rss_mb: 86.3,
      process_peak_rss_scope: 'worker_process_peak_since_start',
      candidate_bundle_count: 18,
      execution_mode: 'local_deterministic',
      runtime_platform: 'TestOS arm64 · Python 3.12.5',
      measured_at: '2026-08-30T12:00:01Z',
      measurement_note: 'Operational telemetry for this run; not a benchmark.',
    },
    snapshot: {
      sha256: 'f'.repeat(64),
      horizon_minutes: 180,
      satellites: [{ id: 'SAT-01', orbit_phase_deg: 0, isolated: false, energy_capacity: 100, storage_capacity: 500 }],
      ground_stations: [{ id: 'GS-01', latitude: 0, longitude: 0, offline_intervals: [] }],
      links: [],
      contact_windows: [{ id: 'CW-01', satellite_id: 'SAT-01', station_id: 'GS-01', interval: { start: 10, end: 30 } }],
      jobs: [{ id: 'JOB-01', criticality: 'critical', deadline: 60 }],
      existing_schedule: [{
        id: 'NOM-01', kind: 'compute', satellite_id: 'SAT-01', interval: { start: 5, end: 10 },
        job_id: 'JOB-01', energy_delta: -10, storage_delta: 20,
      }],
      dataset_provenance: {
        name: 'Committed fixture', source_url: 'https://example.test', license: 'CC BY 4.0',
        version: 'fixture', derived_sha256: 'a'.repeat(64), transformation_manifest: 'fixture-only',
      },
    },
    intent: {
      canonical_digest: 'c'.repeat(64),
      hard_constraints: [],
      soft_preferences: [],
      objective_order: ['coverage'],
      unresolved_ambiguities: [],
      live_interpretation: false,
      gemini_model_id: 'fixture',
      usage_metadata: {},
      fallback_reason: 'test fixture',
    },
    telemetry: [],
    bundles: [{
      id: 'B-01',
      satellite_id: 'SAT-01',
      actions: [{
        id: 'REC-01', kind: 'downlink', satellite_id: 'SAT-01', station_id: 'GS-01',
        interval: { start: 12, end: 20 }, job_id: 'JOB-01', energy_delta: -4, storage_delta: -20,
      }],
      obligations_covered: ['downlink:JOB-01'],
      resources_used: ['SAT-01', 'GS-01'],
      energy_trajectory: [100, 96],
      storage_trajectory: [20, 0],
      costs: { disruption: 1, delay: 0, migration: 0 },
      local_verification_digest: 'd'.repeat(64),
    }],
    plan: {
      selected_bundle_ids: ['B-01'],
      postponed_jobs: [],
      uncovered_obligations: [],
      certainty: 'verified_operation',
      apply_status: 'not_applied',
      objective_components: { disruption: 1, delay: 0, migration: 0 },
      receipts: [{
        request_id: 'receipt-cover', model: 'local', certainty: 'verified_operation', effort: 'bounded',
        command: 'cover', retry_count: 0, latency_ms: 7, receipt: { scope: 'cover' },
        engine_elapsed_ms: 3, engine_peak_rss_kb: 3072, compute_units: 0.25,
        observability: { queue_ms: 1, compute_ms: 3, total_ms: 5 },
      }],
      verification_report: {
        verified: true,
        assurance: 'verified',
        checks: { coverage: true, temporal: true },
        issues: [],
        plan_digest: 'p'.repeat(64),
        input_digest: 'i'.repeat(64),
      },
    },
    audit: [{
      sequence: 1,
      event_id: 'event-1',
      type: 'intent.canonicalized',
      message: 'Mission intent compiled',
      at: '2026-08-30T12:00:00Z',
      component: 'gemini-adk',
      status: 'completed',
      artifact_refs: [],
      retry_count: 0,
      metadata: {},
    }, {
      sequence: 2,
      event_id: 'event-2',
      type: 'verification.passed',
      message: 'Replay passed',
      at: '2026-08-30T12:00:01Z',
      component: 'independent-verifier',
      status: 'completed',
      artifact_refs: [],
      retry_count: 0,
      metadata: {},
    }],
    artifacts: [{
      name: 'mission-replay.zip', content_type: 'application/zip', size: 2048,
      sha256: 'z'.repeat(64), provenance: 'test', storage_uri: '/tmp/replay.zip',
    }, {
      name: 'AI-REVIEW-PROMPT.md', content_type: 'text/markdown', size: 512,
      sha256: 'r'.repeat(64), provenance: 'test', storage_uri: '/tmp/prompt.md',
    }],
  }
}
